name: Notify Discord of Changes

on:
  push:
    branches:
      - main  # 使用你的主要分支名稱

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send notification to Discord
        uses: fjogeleit/http-request-action@v1
        with:
          url: '你的 Discord Webhook URL'  # 替換為你的 Webhook URL
          method: 'POST'
          contentType: 'application/json'
          data: |
            {
              "content": "${{ github.actor }}\n[${{ github.repository }}:${{ github.ref }}] ${{ github.event.commits.length }} new commit(s)\n${{ github.sha }} (${ { github.event.head_commit.message } }) - ${{ github.actor }}"
            }
