name: Notify Discord of Changes

on:
  push:
    branches:
      - main  # 使用你的主要分支名稱

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }} 
        uses: Ilshidur/action-discord@master
        with:
          args: |
            ${{ github.actor }}\n[${{ github.repository }}:${{ github.ref }}] ${{ github.event.commits.length }} new commit(s)\n${{ github.sha }} (${{ github.event.head_commit.message }}) - ${{ github.actor }}
