name: Notify Discord of Changes

on:
  push:
    branches:
      - main  # 使用你的主要分支名稱

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send notification to Discord
        uses: https://github.com/FCheatDev
        with:
          url: 'https://discord.com/api/webhooks/1298592146684907528/Kw0UQNSFuijvnMDbLXsiEYKvlo21QLJQAkHS7r9Mi6en5v3BRlnGzTpEk8vj7Kyhqqps'  # 替換為你的 Webhook URL
          method: 'POST'
          contentType: 'application/json'
          data: |
            {
              "content": "${{ github.actor }}\n[${{ github.repository }}:${{ github.ref }}] ${{ github.event.commits.length }} new commit(s)\n${{ github.sha }} (${ { github.event.head_commit.message } }) - ${{ github.actor }}"
            }
