name: Notify Discord of Changes

on:
  push:
    branches:
      - main  # 使用你的主要分支名稱

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}  # 確保這裡引用的是 GitHub Secrets
        uses: Ilshidur/action-discord@master
        with:
          args: |
            > **[FCheatDev](https://github.com/FCheatDev)**
            > [Version:] ${{ github.sha }}(https://github.com/FCheatDev/Launcher/commit/${{ github.sha }})
            > [Download Launcher](https://getfcheat.web.app/UpdateFile/n.rar)
