name: Notify Discord of Changes

on:
  push:
    branches:
      - main  # 可以改成你的主要分支名稱

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send notification to Discord
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://discord.com/channels/1282192522528952393/1298588329251438612'  # 替換為你的 Webhook URL
          method: 'POST'
          contentType: 'application/json'
          body: '{"content": "檔案有變更已推送到主分支！"}'
