name: Notify Discord of Changes

on:
  push:
    branches:
      - main  # 使用你的主要分支名稱

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get latest commit message
        id: get_commit
        run: echo "commit_message=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}  # 確保這裡引用的是 GitHub Secrets
        uses: Ilshidur/action-discord@master
        with:
          args: |
            > **Update Log** 
            > [Version](https://github.com/FCheatDev/Launcher/commit/${{ github.sha }}) : `${{ github.sha }}`
            > **Update Version** : `${{ env.commit_message }}`
